#version: '1'
services:
  mysql-al:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASS=user
    volumes:
      - mysqlal-data:/var/lib/mysql
volumes:
  mysqlal-data:
    driver: local

